### ISSUE TITLE
Other queues doesn't exist?

### ISSUE THREAD

**Issue by shirArg** [Avnu/igb_avb#10]
Hi, 
I'm trying to use this code, and running into some problems. 
I installed everything, and tried to use the code in the README (or ./startup.sh), with interface eno1. 

I get an error regarding the queues files-
./startup.sh: line 20: /sys/class/net/eno1/queues/tx-1/xps_cpus: No such file or directory
./startup.sh: line 21: /sys/class/net/eno1/queues/tx-2/xps_cpus: No such file or directory
./startup.sh: line 22: /sys/class/net/eno1/queues/tx-3/xps_cpus: No such file or directory

Checking the `queues` folder under ` /sys/class/net/eno1`, there are only `tx-0` and `rx-0` folders. 

I use Ubuntu 18.04, Intel I218-LM NIC. 

Any idea what should I do? I couldn't find any reference to this over the internet...

Thanks

**Comment by pinealservo** [comment]
As I mentioned in your other report, the i218 is not the same as the i210; this functionality is specific to the i210.
