### ISSUE TITLE
Question about strange indentation in e1000_phy.c

### ISSUE THREAD

**Issue by lalevee** [Avnu/igb_avb#12]
In kmod/e1000_phy.c, lines 3294-3300, it seems that parenthesis are missing:
```
        if (locked) **{**
                ready = e1000_is_mphy_ready(hw);
                if (!ready)
                        return -E1000_ERR_PHY;
                E1000_WRITE_REG(hw, E1000_MPHY_ADDR_CTRL, E1000_MPHY_DIS_ACCESS);
          **}**
```
Is that the case?

**Comment by andrew-elder** [comment]
Goo catch! It certainly looks suspicious! Any comments from the authors? Or, can someone ping the authors if they know who they are?

**Comment by psow** [comment]
This is a bug. However, this function is never actually called in the driver, so it's not that urgent - we will fix it in next few days.

**Comment by andrew-elder** [comment]
@psow - thanks for the update. We'll keep an eye out for the fix.

**Comment by jfornal** [comment]
Since it's been resolved and the code fix has been merged I think we can close that issue. Shall we?
