### ISSUE TITLE
README is wrong

### ISSUE THREAD

**Issue by jeez** [Avnu/igb_avb#2]
igb_avb is not the Intel IGB driver, so README.md should be a bit more descriptive, I believe.

**Comment by ghindman** [comment]
Agreed  - looks like the original readme contents from https://github.com/AVnu/OpenAvnu/tree/master/kmod/igb did not make the move.

**Comment by anitha-suresh-zz** [comment]
@ghindman @jeez : PR #4 has been submitted to fix the issue.

**Comment by andrew-elder** [comment]
PR #4 has been merged. @jeez - can you close this one?

**Comment by jeez** [comment]
perfect, thanks!
