### ISSUE TITLE
kernel 5.2.17-rt9 unable to locate correct ethtool.h: ethtool_ops->get_settings not found

### ISSUE THREAD

**Issue by chris-kuhr** [Avnu/igb_avb#24]
Hi *,

I have problems to compile the module for kernel 5.2.17-rt9. The ethtool_ops member ethtool_ops.get_settings and .set_settings can nowhere be found.

Does anyone know where I can find/ how I include the ethtool.h version providing the correct ethtool_ops definition? 

BR,
Ck

**Comment by psow** [comment]
Hi Chris,
Please recheck if you are using the latest source, as this was fixed a while ago in this commit: https://github.com/AVnu/igb_avb/commit/32771dcea930632fef22948ac502416d72ca7cfa

Thanks,
Piotr

**Comment by chris-kuhr** [comment]
Ok, thanks. I made a mistake with my fork...

now the above problem is solved, but a different one occurs.

`igb_select_queue`

has an incompatible signature. 
`igb_netdev_ops.ndo_select_queue` does not have the last argument: 
`u16 (*)(struct net_device *, struct sk_buff *, struct net_device *)  `

**Comment by psow** [comment]
Ok, this is a new one. I should be able to fix it in next few days.

**Comment by psow** [comment]
Ok, I created a pull request #25. You can wait for it to be merged, you can also already test it by applying a patch https://github.com/AVnu/igb_avb/commit/597174eae973744969f96d7280041fd81e2a0d6c.patch

**Comment by chris-kuhr** [comment]
The patch works. Thank you very much!
