### ISSUE TITLE
igb_avb: Unknown symbol __stack_chk_fail (err 0)

### ISSUE THREAD

**Issue by ionutnechita** [Avnu/igb_avb#31]
Hi Avnu Team,

I try to compile and install igb_avb driver on my machine.
But I notice a problem with the module I'm loading into Linux.

# modprobe igb_avb
modprobe: ERROR: could not insert 'igb_avb': Unknown symbol in module, or unknown parameter (see dmesg)
# dmesg | tail -1
[  209.171449] igb_avb: Unknown symbol __stack_chk_fail (err 0 )

HEAD: b659bce1785cfce7daadf7e2bd8785d2afcec199
Environment for build: Yocto Sumo
Kernel: 4.14.212 lts - https://github.com/intel/linux-intel-lts/tree/4.14/base
CFLAGS_append = " -fPIE"

**Comment by psow** [comment]
This is likely due to the -fstack-protector-strong flag. Check your kernel's .config file - you may have stack protector disabled. As an alternative, you can try removing -fstack-protector-strong flag from the Makefile.

**Comment by ionutnechita** [comment]
Hi @psow,

This kernel version, 4.14 does not support the option you are saying. 
CONFIG_STACKPROTECTOR, this parameter is appears starting with version 4.18.

I will try to delete the option -fstack-protector-strong from makefile.

Thanks for the help.

I will come back with feedback.

**Comment by ionutnechita** [comment]
Hi @psow,

By modifying the makefile, it worked.
- https://github.com/ionutnechita/Avnu-igb_avb/commit/9d5b458f7d2f002ffae26c31b54c016975379356
Now I see the network card / igb_avb driver in dmesg.

$ dmesg | grep igb
[    2.269283] igb_avb: loading out-of-tree module taints kernel.
[    2.275908] igb_avb adapter->tx_ring_size 256
[    2.276193] igb: 0000:02:00.0: igb_check_options: VMDq option is not supported.
[    2.329949] igb_avb 0000:02:00.0: added PHC on eth0
[    2.329953] igb_avb 0000:02:00.0: Intel(R) Gigabit Ethernet Network Connection
[    2.329956] igb_avb 0000:02:00.0: eth0: (PCIe:2.5GT/s:Width x1)
[    2.329959] igb_avb 0000:02:00.0 eth0: MAC: xx:xx:xx:xx:xx:xx
[    2.331138] igb_avb 0000:02:00.0: eth0: PBA No: 000300-000
[    2.331170] igb_avb 0000:02:00.0: LRO is disabled
[    2.331172] igb_avb 0000:02:00.0: Using MSI-X interrupts. 4 rx queue(s), 4 tx queue(s)
[    9.841069] igb_avb 0000:02:00.0 eth0: igb: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX

Thanks.

It's fine for close this ticket.
