### ISSUE TITLE
raspberry  cm4 igb_main.c:7415:17: error: implicit declaration of function ‘read_barrier_depends’ [-Werror=implicit-function-declaration]  7415 |                 read_barrier_depends();

### ISSUE THREAD

**Issue by 652436962** [Avnu/igb_avb#34]
hardware   cm4+inter i210
os:    ubuntu 20.04
build:
cd igb_avb/
make kmod

igb_main.c:7415:17: error: implicit declaration of function ‘read_barrier_depends’ [-Werror=implicit-function-declaration]
 7415 |                 read_barrier_depends();

**Comment by hieronymus-j** [comment]
Hello,
did you find a solution? I get the exact error message.
Ubuntu 22.04 Kernel 5.15.0-60-generic

**Comment by MarcinMiklas** [comment]
read_barrier_depends() is a macro which was removed in newer kernels, this commit solves the issue:
https://github.com/Avnu/igb_avb/pull/35/commits/96aa657501d615af74e04e8d4c6c78ccf1be95a2
