### ISSUE TITLE
Module does not build on kernel version 6.8

### ISSUE THREAD

**Issue by mrCamelCase** [Avnu/igb_avb#41]
Greetings! This is my first time filing an issue on an open source project, so you'll have to forgive me if I forget any process-related things, leave out some crucial information, or simply misunderstand the problem I am encountering. Nevertheless, I believe I have discovered an incompatibility between this driver and the 6.8 kernel.

Attempting to install the driver using DKMS (`dkms install igb_avb/5.3.2_AVB`), I see the following:
```
make -j12 KERNELRELEASE=6.8.0-40-generic -C kmod SUBDIRS=/var/lib/dkms/igb_avb/5.3.2_AVB/build....(bad exit status: 2)
ERROR (dkms apport): binary package for igb_avb: 5.3.2_AVB not found
Error! Bad return status for module build on kernel: 6.8.0-40-generic (x86_64)
Consult /var/lib/dkms/igb_avb/5.3.2_AVB/build/make.log for more information.
```
The `make.log` can be found [here](https://github.com/user-attachments/files/16801298/make.log). I don't know enough about the interactions between the driver and the Linux kernel to figure out why those particular errors appear, though I do think that the "no previous prototype" warnings are probably because I am missing some kernel headers or something. Unsure if or how those are related.

Attempting a simple `make kmod` in the appropriate directory yields the same errors (though not the prototype warnings). Performing the same DKMS command on `6.5.0-45-generic` works as intended, so this is the workaround I am using for the time being.

My full `uname -a` for good measure:
```
Linux hostname 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

I appreciate the support - please let me know if I can provide any more information!
-Sam

**Comment by MarcinMiklas** [comment]
Hello,

Please check if this fix for kernels >= 6.8.0 works for you

https://github.com/Avnu/igb_avb/pull/43

I was only able to check if it builds. Currently, I have no way to test it on hardware with 6.8.0 kernel version.

Regards,
Marcin

**Comment by mrCamelCase** [comment]
Hello Marcin,

I can confirm that it both builds and runs on 6.8.0. Should I review and approve the PR?
-Sam

**Comment by MarcinMiklas** [comment]
Yes, please do it.

**Comment by MarcinMiklas** [comment]
Fixed
