### ISSUE TITLE
igb_avb versioned releases

### ISSUE THREAD

**Issue by tvyas** [Avnu/igb_avb#7]
We'd like to propose versioned releases of igb_avb so that we can start pushing changes to the master and tag newer version as and when needed.

Since the last tagged release of Open AVnu was v1.1 released in Dec. 2013 https://github.com/AVnu/OpenAvnu/releases, we propose **v1.1.1** for igb_avb.

Please comment as needed.

Thanks.

**Comment by tvyas** [comment]
Ping. Any thoughts here ?

Thank,
Tarun

**Comment by andrew-elder** [comment]
Hmmm gptp has a pull request in place that describes v1.0. I think I like the three digit version better. @tvyas - can you say who "we" is that is making this proposal?

**Comment by tvyas** [comment]
Thanks Andrew ! 

I'm a part of Gavin Hindman's team at OTC, Intel.

**Comment by andrew-elder** [comment]
I haven't been tracking changes in detail. Any release notes/comments to with the v1.1.1 release?

**Comment by tvyas** [comment]
We can do "This is mostly a bug fix release addressing build issues, potential memory corruptions and race conditions.".

**Comment by andrew-elder** [comment]
Tagged.

**Comment by tvyas** [comment]
Thanks !
